### PR TITLE
Do not save after an operation.

### LINKED ISSUE #114: Consider stopping automatically saving files
When the extension automatically inserts a licensing header, it automatically saves the file afterwards.

I propose to discontinue this behavior for two reasons:

* First, it violates the separation of concerns. The extension's purpose is to insert license headers, saving files is what the user does, and doing it when it's not asked might degrade user experience on machines with slow storage or remote clients.

* Second, the user experience when automatic header insertion is not disabled is horrible. Every time I create a temporary file, VSCode creates a tab for it, and then immediately the extension writes the license header, proceeds to save the file, and I am greeted with a save dialog for a file I never intended to save.

If my proposal is accepted I am willing to submit a pull request to implement it.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
Fixes #114.

This PR removes all `save` calls from the extension's source code, and also removed and replaced some deprecated function calls.

### CODE REVIEW

**Comment by ymotongpoo** [comment]
Hi @teo-tsirpanis, I misread the original issue comment. Could you make change to be an option? i.e. Could you leave an option to do autosave? You may add an extension setting for it.

**Comment by ymotongpoo** [comment]
@teo-tsirpanis kindly ping. do you have any comments on my request? Again, thank you for your contribution.

**Comment by teo-tsirpanis** [comment]
Hello, I am busy these days; it will take me some time until I can work on it.

**Comment by teo-tsirpanis** [comment]
I am working on it. How about never saving after the automatic header insertion on a new file only? It would address my second bullet point in #114 by default, and I don't imagine anyone wanting this behavior.

**Comment by ymotongpoo** [comment]
How do you differentiate "temporary" file and intended new files?

**Comment by teo-tsirpanis** [comment]
OK @ymotongpoo, I added the configuration option. Can you take a look?

**Review by ymotongpoo — APPROVED** [review]
Thank you for your changes, @teo-tsirpanis. Please make sure to add your name on `CONTRIBUTORS` file.

**Comment by teo-tsirpanis** [comment]
It already is @ymotongpoo, I have contributed before: https://github.com/ymotongpoo/vsc-licenser/blob/2272819f6855dd32705d18f83684df716623f844/CONTRIBUTORS#L13

**Comment by ymotongpoo** [comment]
Thanks for the repeated contribution, @teo-tsirpanis!

**Pull request merged**
