### PR TITLE
fix: upgrade from tslint to eslint as the former is deprecated

### PR DESCRIPTION
**Pull request by akkumar**
Migrate from tslint to eslint ..

`tslint-to-eslint-config.log says the following: 

```
3 ESLint rules behave differently from their TSLint counterparts:
  * brace-style:
    - ESLint's brace-style will check all tokens.
  * eqeqeq:
    - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.
  * no-underscore-dangle:
    - Leading or trailing underscores (_) on identifiers will now be forbidden.

1 rule is not known by tslint-to-eslint-config to have an ESLint equivalent:
  * tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "whitespace".
```

### CODE REVIEW

**Comment by akkumar** [comment]
There is a very nice eslint plugin to find deprecated API - eslint-plugin-deprecation  . 

Currently - that plugin does not seem to support eslint 8.x though - #37 .  

Hence followed the hack as per the discussion in that thread.

**Review by ymotongpoo — APPROVED** [review]
Thanks for the update! LGTM.

**Review by ymotongpoo — CHANGES_REQUESTED** [review]
Need to resolve conflicts in package-lock.json

**Comment by akkumar** [comment]
@ymotongpoo - FYI . Committed the changes.

**Review by ymotongpoo — APPROVED** [review]
@akkumar Thank you for the housekeeping! LGTM

**Pull request merged**
