### PR TITLE
Update agplv3.ts

### PR DESCRIPTION
**Pull request by ToastHawaii**
Make agplv3 more like gplv3 and add product name

### CODE REVIEW

**Comment by welljsjs** [comment]
LGTM but I think you're missing a line in `extension.ts`: https://github.com/ymotongpoo/vsc-licenser/blob/626d0cb3a51aa25a604f91b0141aa9a92edcce55/src/extension.ts#L87

should be 

```ts
["AGPLV3", { displayName: "AGPLv3", creatorFn: (author, projectName) => new AGPLv3(author, projectName) }],
```

**Review by welljsjs — APPROVED** [review]
@ymotongpoo Sorry to wake you up, but is this repo still being maintained? Otherwise we might consider publishing our own fork
Thanks!

**Comment by ymotongpoo** [comment]
@welljsjs First, thanks for the comment. I was busy in last 3 weeks and missed the notification of this PR. Sorry about that.

WRT the maintenance, this repo is reactively maintained, but if you'd like to fork, it's up to you. As this is OSS project and as long as you follow the license, I have no objection.

**Comment by welljsjs** [comment]
@ymotongpoo 
Nw, thanks for the quick reply. 

Ok good to know, I was just making sure you're still interested in this project, without any expectations - it surely doesn't take a trivial amount of effort to maintain an OSS project so as far as I'm concerned we're really thankful for this project!

**Comment by ymotongpoo** [comment]
@ToastHawaii Thanks for the suggestion. Unfortunately, the template is not free form but there's a fixed format defined. (See "How to Apply These Terms to Your New Programs" section here.)
https://www.gnu.org/licenses/agpl-3.0.en.html

If you have the counter evidence that supports your suggestion, I will accept this PR. Until then, I keep this as draft.

**Comment by ToastHawaii** [comment]
Hmm.... I'm not sure I understand you correctly. I have used the GPL source code as a template.
I can't see much difference between the GPL "How to Apply These Terms to Your New Programs" https://www.gnu.org/licenses/gpl-3.0.en.html and the AGPL Version.

Is the GPL template also not a free form?

**Comment by ymotongpoo** [comment]
AGPL v3 is not GPL license. AGPL = Affero General Public License

And ditto as GPL. If you'd like to use your own template, please use the custom license header feature. I mark this as resolved.

**Pull request closed without merging**
